
tasks:
  - init: npm install && npm run build
    command: "npx -y http-server --mime-types '{ ''application/javascript'': [''js''] }' --cors"


vscode:
  extensions:
    - Gruntfuggly.todo-tree

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart